#!/usr/bin/bash


# This file holds all the variables that will be loaded and used to setup
# your Debian installation.  Please customize this for EACH computer and save
# it in something like the ~/Setup directory (can be configured to use a
# different directory in the *-setup.sh script itself.  Doing so will prevent
# merge errors in case you do a git pull later for a newer version.


status_dir='status' # Holds script status between reboots, can be absolute path or relative (to script dir)
rm_dotfiles=1 # Remove all old .dotfiles (from prior Linux distributions)
GRUB_CMDLINE_LINUX_DEFAULT='quiet splash' # To be copied into /etc/default/grub, parms like "pci=noaer" go here
ssd=1 # Uncomment if installed to an SSD
gdm_inhibit_ac=1 # Inhibit suspend if on AC power but not logged (for servers and SSH access)
ignore_lid_switch=1 # Ignore suspend on closing lid tweak
install_windscribe=1 # VPN with slick Linux GUI!
load_mimetypes=1 # Load Nautilus mime types for Neovim
patched_font='Hack Nerd Font 9' # Because only 1337 hax0rz use a font called Hack
boot_logo='gnome-logo.png' # Can also be ubuntu-gnome-logo.png if you like nostalgia! Comment this variable if you want to keep the stock Ubuntu logo

# If using 1920x1080 screen resolution, highly recommend changing the default
# terminal window size in *-dconf.txt to 100 cols by 50 rows
# Smaller screen resolutions should stick to 80x35


apt_purges=(
	thunderbird # I only use web-mail, so I don't need this...  Comment it out if you still connect to an IMAP email server!
	branding-ubuntu # Why the hell is Ubuntu sticking their logo on packages they didn't make, like OpenOffice, Eclipse, and even Solitaire?!  WTF...
	power-profiles-daemon # Gnome power profiles saves battery by just limiting your CPU all the time, TLP is smarter
)


# Snaps will be removed one-by-one, so make sure the order is correct to avoid dependency conflicts!
# If you wish to keep snaps, comment out the contents of this array
snap_purges=(
	firefox
	snap-store
	snapd-desktop-integration
	gtk-common-themes
	gnome-3-38-2004
	core20
	bare
	snapd
)


ppas=(
	ppa:mozillateam/ppa # For a Firefox deb instead of stupid snaps
)


apt_installs=(
	# OS packages
	ffmpegthumbnailer # totem-video-thumbnailer is broken in 22.04
	openssh-server
	tlp
	tlp-rdw
	flatpak
	gnome-software-plugin-flatpak
	gufw
	catfish # Since file searching in Nautilus sucks (still can't sort search results)
	gir1.2-gtop-2.0 # Required for the system-monitor Gnome extension
	vlc # Totem often doesn't work; VLC can fix subtitle timing or step frame-by-frame
	libavcodec-extra
	# libdvd-pkg # Uncomment to watch DVD movies with internal/external DVD drive
	nautilus-dropbox

	# Development packages
	neovim
	python3-neovim
	ipython3
	python3-venv

	# Apps
	gimp
	gimp-data-extras
	inkscape
	inkscape-open-symbols
	gnucash
	python3-gnucash
	wine # For playing Windows games
)


flatpaks=(
	com.google.Chrome
	com.github.xournalpp.xournalpp
	com.github.johnfactotum.Foliate
	org.kde.kdenlive
	org.libretro.RetroArch
	com.stepmania.StepMania # DDR uses vim arrows! Just another reason why vim > emacs
	com.github.iwalton3.jellyfin-media-player
)


extension_urls=(
	https://extensions.gnome.org/extension/906/sound-output-device-chooser/
	https://extensions.gnome.org/extension/72/recent-items/
	https://extensions.gnome.org/extension/779/clipboard-indicator/
	https://extensions.gnome.org/extension/3010/system-monitor-next/
)


environment=(
	# Don't triple-buffer the mouse pointer (as per Ubuntu docs for more responsive mouse)
	MUTTER_DEBUG_ENABLE_ATOMIC_KMS=0 # Ubuntu 22.04
	# MUTTER_DEBUG_FORCE_KMS_MODE=simple # Ubuntu 22.10
	MOZ_ENABLE_WAYLAND=1 # Smoother scrolling with Firefox on Wayland
)
