#!/usr/bin/bash


# This file holds all the variables that will be loaded and used to setup
# your Debian installation.  Please customize this for EACH computer and save
# it in something like the ~/Setup directory (can be configured to use a
# different directory in the *-setup.sh script itself.  Doing so will prevent
# merge errors in case you do a git pull later for a newer version.


status_dir='status' # Holds script status between reboots, can be absolute path or relative (to script dir)
rm_dotfiles=1 # Remove all old .dotfiles (from prior Linux distributions)
GRUB_CMDLINE_LINUX_DEFAULT='quiet splash' # To be copied into /etc/default/grub, parms like "pci=noaer" go here
ssd=1 # Uncomment if installed to an SSD
gdm_inhibit_ac=1 # Inhibit suspend if on AC power but not logged (for servers and SSH access)
ignore_lid_switch=1 # Ignore suspend on closing lid tweak
install_windscribe=1 # VPN with slick Linux GUI!
load_mimetypes=1 # Load Nautilus mime types for Neovim
patched_font='Hack Nerd Font 9'
boot_logo='ubuntu-gnome-logo.png' # Can also be ubuntu-gnome-logo.png if you like nostalgia! Comment this variable if you want to keep the stock Ubuntu logo

# If using 1920x1080 screen resolution, highly recommend changing the default
# terminal window size in *-dconf.txt to 100 cols by 50 rows
# Smaller screen resolutions should stick to 80x35 or 80x40

# For minimize and maximize buttons on window title bars, add this line to *-gsettings.txt
# org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'


apt_purges=(
	thunderbird # I only use web-mail, so I don't need this...  Comment it out if you still connect to an IMAP email server!
	branding-ubuntu # Why the hell is Ubuntu sticking their logo on packages they didn't make, like OpenOffice, Eclipse, and even Solitaire?!  WTF...
)


# Snaps will be removed one-by-one, so make sure the order is correct to avoid dependency conflicts!
# If you wish to keep snaps, comment out the contents of this array
snap_purges=(
	firefox
	snap-store
	snapd-desktop-integration
	gtk-common-themes
	gnome-3-38-2004
	core20
	bare
	snapd
)


ppas=(
	ppa:linrunner/tlp # For latest versions of TLP
	ppa:mozillateam/ppa # For a Firefox deb instead of stupid snaps
)


apt_installs=(
	openssh-server
	tlp
	tlp-rdw
	flatpak
	gnome-software-plugin-flatpak
	gufw
	vlc
	# libavcodec-extra # Is this needed?
	ipython3
	catfish # Since file searching in Nautilus sucks...
	gir1.2-gtop-2.0 # Required for the system-monitor Gnome extension
	# libdvd-pkg # Uncomment to watch DVD movies with internal/external DVD drive
	nautilus-dropbox
	neovim
	python3-neovim
	gimp
	gimp-data-extras
	inkscape
	inkscape-open-symbols
	gnucash
	python3-gnucash
	wine
)


flatpaks=(
	com.google.Chrome
	com.github.xournalpp.xournalpp
	com.github.johnfactotum.Foliate
	org.kde.kdenlive
	org.libretro.RetroArch
	com.stepmania.StepMania
	com.github.iwalton3.jellyfin-media-player
)


extension_urls=(
	https://extensions.gnome.org/extension/906/sound-output-device-chooser/
	https://extensions.gnome.org/extension/72/recent-items/
	https://extensions.gnome.org/extension/779/clipboard-indicator/
	https://extensions.gnome.org/extension/3010/system-monitor-next/
)

